[package]
name = "dub_dump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
crossterm = "0.27.0"
rodio = "0.17.3"
